In [2]:
from numpy import *  

In [4]:
arr=array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
print(arr.dtype)

int32


In [7]:
arr=array([1,2,3.3,4.5,8],int)
print(arr)

[1 2 3 4 8]


# Different types of creating arrays

In [9]:
arr=linspace(0,15,9)
arr

array([ 0.   ,  1.875,  3.75 ,  5.625,  7.5  ,  9.375, 11.25 , 13.125,
       15.   ])

In [10]:
arr=linspace(0,15) # 50 parts automatically 
print(arr)



[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [11]:
arr=arange(1,50,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [12]:
arr=logspace(1,40,5)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [14]:
arr= zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [15]:
arr= zeros(5,int)
print(arr)

[0 0 0 0 0]


In [16]:
arr= ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [17]:
arr= ones(5,int)
print(arr)

[1 1 1 1 1]


# array addition


#1. Scalar Addition

In [19]:
arr=array([1,3,4,2,7])
arr=arr+5
print(arr)

[ 6  8  9  7 12]



#1. Vectorized Addition

In [21]:
arr1=arr=array([1,3,4,2,7])
arr2=array([1,2,3,4,5])
print("Addition: ",arr1+arr2)

Addition:  [ 2  5  7  6 12]


In [22]:
arr=array([44,33,55,22,66])
print("Sine:",sin(arr))
print("Cosine:",cos(arr))
print("Tangent:",tan(arr))
print("Logarithn:",log(arr))
print("Minimum:",min(arr))
print("Maximum:",max(arr))
print("Square root:",sqrt(arr))

Sine: [ 0.01770193  0.99991186 -0.99975517 -0.00885131 -0.02655115]
Cosine: [ 0.99984331 -0.01327675  0.02212676 -0.99996083 -0.99964746]
Tangent: [ 1.77046993e-02 -7.53130148e+01 -4.51830879e+01  8.85165604e-03
  2.65605178e-02]
Logarithn: [3.78418963 3.49650756 4.00733319 3.09104245 4.18965474]
Minimum: 22
Maximum: 66
Square root: [6.63324958 5.74456265 7.41619849 4.69041576 8.1240384 ]


In [23]:
arr1=array([33,22,44,55,66,77])
arr2=array([45,99,67,98,34,9,23])
print(concatenate((arr1,arr2)))

[33 22 44 55 66 77 45 99 67 98 34  9 23]


# Aliasing

In [27]:
arr1=array([22,33,44,55,66])
arr2=arr1 #Aliasing->Same like shallow copy
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
arr1[1]=0
print(arr1)
print(arr2)

[22 33 44 55 66]
[22 33 44 55 66]
273070424
273070424
[22  0 44 55 66]
[22  0 44 55 66]


In [35]:
from numpy import *
arr1=array([22,33,44,55,66])
#shallow copy
arr2=arr1.view()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
arr1[1]=0
print(arr1)
print(arr2)

[22 33 44 55 66]
[22 33 44 55 66]
273069024
273070344
[22  0 44 55 66]
[22  0 44 55 66]


In [28]:
from numpy import *
arr1=array([22,33,44,55,66])
#deep copy
arr2=arr1.copy()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
arr2[1]=0
print(arr1)
print(arr2)

[22 33 44 55 66]
[22 33 44 55 66]
273071784
273070704
[22 33 44 55 66]
[22  0 44 55 66]


In [29]:
from numpy import *
#matrix
arr1=array([[1,2,3],[4,5,6]])
print("Dimension:",arr1.ndim)
print("Shape:",arr1.shape)
print("Size:",arr1.size)

Dimension: 2
Shape: (2, 3)
Size: 6


In [30]:
from numpy import *
arr1=array([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12]
])
arr2=arr1.flatten() #Converts into 1D
print(arr2)

arr3=array([
    [
        [1,2,3],[9,10,11],[4,5,6],[7,8,9],[1,2,3]
    ]
])
arr4=arr3.flatten()
print(arr4)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  9 10 11  4  5  6  7  8  9  1  2  3]


In [32]:
from numpy import*
arr3=array([
    [
        [1,2,3],[9,10,11],[4,5,6],[7,8,9],[1,2,3]
    ]
])
arr4=arr3.flatten()
arr5=arr4.reshape(5,3) #it will reshape the array to a 2D array of order 5X3
print(arr5)
print("-------------------------------")
arr1=array([[1,2,3,2],[4,5,6,7],[1,2,3,4]])
arr2=arr1.reshape(2,2,3)
print(arr2)


[[ 1  2  3]
 [ 9 10 11]
 [ 4  5  6]
 [ 7  8  9]
 [ 1  2  3]]
-------------------------------
[[[1 2 3]
  [2 4 5]]

 [[6 7 1]
  [2 3 4]]]


In [33]:
from numpy  import *
arr1=array([[1,2,3,4],[2,1,3,4]])

m=matrix(arr1) # converts array into matrix
print(m)

print("--------------------------------")
# creating matrix
m1=matrix('1 2 3 4;4 3 2 1;1 2 3 4;4 3 2 1')
print(m1)




[[1 2 3 4]
 [2 1 3 4]]
--------------------------------
[[1 2 3 4]
 [4 3 2 1]
 [1 2 3 4]
 [4 3 2 1]]


In [34]:

m1=matrix('1,2,3;6 7 8;3,3,3')
print(m1)
print("===================")
print("Diagonal:",diagonal(m1))
print("===================")
print("Max:",m1.max())
print("===================")
print("Min:",m1.min())
print("===================")

print("+++++++++++++++++++++++")
m2=matrix('11,22,33;66 77 8;33,33,33')
print(m2)
print("+++++++++++++++++++++++")
print("Addition:")
print(m1+m2)
print("------------------------")
print("Subtraction:")
print(m1-m2)
print("***********************")
print("Multiplication:")
print(m1*m2)

[[1 2 3]
 [6 7 8]
 [3 3 3]]
Diagonal: [1 7 3]
Max: 8
Min: 1
+++++++++++++++++++++++
[[11 22 33]
 [66 77  8]
 [33 33 33]]
+++++++++++++++++++++++
Addition:
[[12 24 36]
 [72 84 16]
 [36 36 36]]
------------------------
Subtraction:
[[-10 -20 -30]
 [-60 -70   0]
 [-30 -30 -30]]
***********************
Multiplication:
[[242 275 148]
 [792 935 518]
 [330 396 222]]
